# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170916_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
