# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_edited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='objects_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_count',
            field=models.IntegerField(default=0),
        ),
    ]
