# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170917_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
