# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170917_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_count',
        ),
    ]
