# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_auto_20170917_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('author', 'content_type', 'object_id')]),
        ),
    ]
