# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('title', models.CharField(default=b'', max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
